[package]
name = "junita_fuchsia_async"
description = "Async runtime for Fuchsia using Zircon ports"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/junita_fuchsia_async"
rust-version.workspace = true
keywords = ["fuchsia", "async", "executor", "junita"]
categories = ["asynchronous", "os::fuchsia-api-bindings"]

[lib]
crate-type = ["lib"]

[features]
default = []

[dependencies]
junita_fuchsia_zircon = { path = "../junita_fuchsia_zircon", version = "0.1.12" }
futures = "0.3"
pin-project-lite = "0.2"
